$axure.loadCurrentPage(
  (function () {
    var _ = function () {
      var r = {},
        a = arguments;
      for (var i = 0; i < a.length; i += 2) r[a[i]] = a[i + 1];
      return r;
    };
    var _creator = function () {
      return _(
        b,
        c,
        d,
        e,
        f,
        _(g, h, i, _(j, k, l, k)),
        m,
        [],
        n,
        _(h, o),
        p,
        [q],
        r,
        _(
          s,
          t,
          u,
          v,
          g,
          w,
          x,
          _(),
          y,
          [],
          z,
          _(
            A,
            B,
            C,
            D,
            E,
            _(F, G, H, I),
            J,
            null,
            K,
            L,
            L,
            M,
            N,
            O,
            null,
            P,
            Q,
            R,
            S,
            T,
            U,
            V,
            Q,
            W,
            X,
            _(F, G, H, Y),
            Z,
            Q,
            ba,
            bb,
            _(
              bc,
              bd,
              be,
              bf,
              bg,
              bf,
              bh,
              bf,
              bi,
              k,
              H,
              _(bj, bk, bl, bk, bm, bk, bn, bo),
            ),
            i,
            _(j, k, l, k),
          ),
          bp,
          _(),
          bq,
          _(),
          br,
          _(bs, [
            _(
              bt,
              bu,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                i,
                _(j, bC, l, bD),
                A,
                bE,
                X,
                _(F, G, H, bF),
                E,
                _(F, G, H, bG),
                Z,
                bH,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              bK,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bL,
                _(F, G, H, bG, bM, bN),
                i,
                _(j, bO, l, bP),
                A,
                bQ,
                bR,
                _(bS, bT, bU, bV),
                bW,
                bX,
                bY,
                D,
                bZ,
                ca,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              cb,
              bv,
              h,
              bw,
              cc,
              u,
              cd,
              bz,
              cd,
              bA,
              bB,
              z,
              _(
                i,
                _(j, ce, l, cf),
                cg,
                _(ch, _(A, ci), cj, _(A, ck)),
                A,
                cl,
                bR,
                _(bS, cm, bU, cn),
                Z,
                co,
                bW,
                bX,
              ),
              cp,
              bd,
              bp,
              _(),
              bI,
              _(),
              cq,
              cr,
            ),
            _(
              bt,
              cs,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                i,
                _(j, ct, l, cu),
                A,
                cv,
                bR,
                _(bS, cw, bU, cx),
                bW,
                cy,
                cg,
                _(cz, _(E, _(F, G, H, cA))),
              ),
              bp,
              _(),
              bI,
              _(),
              bq,
              _(
                cB,
                _(cC, cD, cE, cF, cG, [
                  _(cE, h, cH, h, cI, bd, cJ, cK, cL, [
                    _(
                      cM,
                      cN,
                      cE,
                      cO,
                      cP,
                      cQ,
                      cR,
                      _(cS, _(h, cO)),
                      cT,
                      _(cU, r, b, cV, cW, bB),
                      cX,
                      cY,
                    ),
                  ]),
                ]),
              ),
              cZ,
              bB,
              bJ,
              bd,
            ),
            _(
              bt,
              da,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                i,
                _(j, ct, l, cu),
                A,
                cv,
                bR,
                _(bS, db, bU, cx),
                bW,
                cy,
                cg,
                _(cz, _(E, _(F, G, H, cA))),
              ),
              bp,
              _(),
              bI,
              _(),
              bq,
              _(
                cB,
                _(cC, cD, cE, cF, cG, [
                  _(cE, h, cH, h, cI, bd, cJ, cK, cL, [
                    _(
                      cM,
                      cN,
                      cE,
                      cO,
                      cP,
                      cQ,
                      cR,
                      _(cS, _(h, cO)),
                      cT,
                      _(cU, r, b, cV, cW, bB),
                      cX,
                      cY,
                    ),
                  ]),
                ]),
              ),
              cZ,
              bB,
              bJ,
              bd,
            ),
            _(
              bt,
              dc,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                dd,
                de,
                bL,
                _(F, G, H, I, bM, bN),
                i,
                _(j, df, l, dg),
                A,
                dh,
                bR,
                _(bS, di, bU, dj),
                bY,
                D,
                bW,
                dk,
                bZ,
                ca,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              dl,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bL,
                _(F, G, H, bG, bM, bN),
                i,
                _(j, bO, l, bP),
                A,
                bQ,
                bR,
                _(bS, bT, bU, dm),
                bW,
                bX,
                bY,
                D,
                bZ,
                ca,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              dn,
              bv,
              h,
              bw,
              cc,
              u,
              cd,
              bz,
              cd,
              bA,
              bB,
              z,
              _(
                i,
                _(j, ce, l, cf),
                cg,
                _(ch, _(A, ci), cj, _(A, ck)),
                A,
                cl,
                bR,
                _(bS, cm, bU, dp),
                Z,
                co,
                bW,
                bX,
              ),
              cp,
              bd,
              bp,
              _(),
              bI,
              _(),
              cq,
              dq,
            ),
            _(
              bt,
              dr,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bL,
                _(F, G, H, bG, bM, bN),
                i,
                _(j, bO, l, bP),
                A,
                bQ,
                bR,
                _(bS, bT, bU, ds),
                bW,
                bX,
                bY,
                D,
                bZ,
                ca,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              dt,
              bv,
              h,
              bw,
              cc,
              u,
              cd,
              bz,
              cd,
              bA,
              bB,
              z,
              _(
                i,
                _(j, ce, l, cf),
                cg,
                _(ch, _(A, ci), cj, _(A, ck)),
                A,
                cl,
                bR,
                _(bS, cm, bU, du),
                Z,
                co,
                bW,
                bX,
              ),
              cp,
              bd,
              bp,
              _(),
              bI,
              _(),
              cq,
              dv,
            ),
          ]),
        ),
        dw,
        _(),
        dx,
        _(
          dy,
          _(dz, dA),
          dB,
          _(dz, dC),
          dD,
          _(dz, dE),
          dF,
          _(dz, dG),
          dH,
          _(dz, dI),
          dJ,
          _(dz, dK),
          dL,
          _(dz, dM),
          dN,
          _(dz, dO),
          dP,
          _(dz, dQ),
          dR,
          _(dz, dS),
        ),
      );
    };
    var b = "url",
      c = "add_llm.html",
      d = "generationDate",
      e = new Date(1721496785703.5),
      f = "defaultAdaptiveView",
      g = "name",
      h = "",
      i = "size",
      j = "width",
      k = 0,
      l = "height",
      m = "adaptiveViews",
      n = "sketchKeys",
      o = "s0",
      p = "variables",
      q = "OnLoadVariable",
      r = "page",
      s = "packageId",
      t = "1a77ce1c353c423097bc74e8062376d1",
      u = "type",
      v = "Axure:Page",
      w = "Add LLM",
      x = "notes",
      y = "annotations",
      z = "style",
      A = "baseStyle",
      B = "627587b6038d43cca051c114ac41ad32",
      C = "pageAlignment",
      D = "center",
      E = "fill",
      F = "fillType",
      G = "solid",
      H = "color",
      I = 0xffffffff,
      J = "image",
      K = "imageAlignment",
      L = "near",
      M = "imageRepeat",
      N = "auto",
      O = "favicon",
      P = "sketchFactor",
      Q = "0",
      R = "colorStyle",
      S = "appliedColor",
      T = "fontName",
      U = "Applied Font",
      V = "borderWidth",
      W = "borderVisibility",
      X = "borderFill",
      Y = 0xff797979,
      Z = "cornerRadius",
      ba = "cornerVisibility",
      bb = "outerShadow",
      bc = "on",
      bd = false,
      be = "offsetX",
      bf = 5,
      bg = "offsetY",
      bh = "blurRadius",
      bi = "spread",
      bj = "r",
      bk = 0,
      bl = "g",
      bm = "b",
      bn = "a",
      bo = 0.349019607843137,
      bp = "adaptiveStyles",
      bq = "interactionMap",
      br = "diagram",
      bs = "objects",
      bt = "id",
      bu = "af8a43d76517400495678f6722be0c24",
      bv = "label",
      bw = "friendlyType",
      bx = "Rectangle",
      by = "vectorShape",
      bz = "styleType",
      bA = "visible",
      bB = true,
      bC = 999,
      bD = 80,
      bE = "4b7bfc596114427989e10bb0b557d0ce",
      bF = 0xff00000a,
      bG = 0xff039d12,
      bH = "10",
      bI = "imageOverrides",
      bJ = "generateCompound",
      bK = "70809451c0f84ce5a6d3eff60f764c93",
      bL = "foreGroundFill",
      bM = "opacity",
      bN = 1,
      bO = 195,
      bP = 30,
      bQ = "2285372321d148ec80932747449c36c9",
      bR = "location",
      bS = "x",
      bT = 70,
      bU = "y",
      bV = 160,
      bW = "fontSize",
      bX = "19px",
      bY = "horizontalAlignment",
      bZ = "verticalAlignment",
      ca = "middle",
      cb = "7e5493fa10e94784b19ac0630e24fc51",
      cc = "Text Field",
      cd = "textBox",
      ce = 630,
      cf = 35,
      cg = "stateStyles",
      ch = "hint",
      ci = "4889d666e8ad4c5e81e59863039a5cc0",
      cj = "disabled",
      ck = "9bd0236217a94d89b0314c8c7fc75f16",
      cl = "44157808f2934100b68f2394a66b2bba",
      cm = 300,
      cn = 158,
      co = "4",
      cp = "HideHintOnFocused",
      cq = "placeholderText",
      cr = "Escriba el nombre de su LLM",
      cs = "8ba0a702eb3a42388a8d1808178e5049",
      ct = 140,
      cu = 40,
      cv = "cd64754845384de3872fb4a066432c1f",
      cw = 790,
      cx = 410,
      cy = "17px",
      cz = "mouseOver",
      cA = 0xff0000ff,
      cB = "onClick",
      cC = "eventType",
      cD = "OnClick",
      cE = "description",
      cF = "Click or Tap",
      cG = "cases",
      cH = "conditionString",
      cI = "isNewIfGroup",
      cJ = "caseColorHex",
      cK = "AB68FF",
      cL = "actions",
      cM = "action",
      cN = "linkWindow",
      cO = "Open LLMs List in Current Window",
      cP = "displayName",
      cQ = "Open Link",
      cR = "actionInfoDescriptions",
      cS = "LLMs List",
      cT = "target",
      cU = "targetType",
      cV = "llms_list.html",
      cW = "includeVariables",
      cX = "linkType",
      cY = "current",
      cZ = "tabbable",
      da = "2e6fdf69d4444916b4d8fad074bb2730",
      db = 98,
      dc = "5b589a1121924bb8977c40c1ce35702e",
      dd = "fontWeight",
      de = "700",
      df = 961,
      dg = 38,
      dh = "1111111151944dfba49f67fd55eb1f88",
      di = 19,
      dj = 21,
      dk = "36px",
      dl = "e79bb0f073a74f05bf68ccaeacb3f0d7",
      dm = 217,
      dn = "201fb085a7834ae5bc02792d58719453",
      dp = 215,
      dq = "Escriba el URL de la API de su LLM",
      dr = "12d97b01c67f4e97ba79c7a8f3691a19",
      ds = 277,
      dt = "2f93abfd602f4e199ef4271ce40617d2",
      du = 275,
      dv = "Escriba la API KEY de ser necesaria",
      dw = "masters",
      dx = "objectPaths",
      dy = "af8a43d76517400495678f6722be0c24",
      dz = "scriptId",
      dA = "u231",
      dB = "70809451c0f84ce5a6d3eff60f764c93",
      dC = "u232",
      dD = "7e5493fa10e94784b19ac0630e24fc51",
      dE = "u233",
      dF = "8ba0a702eb3a42388a8d1808178e5049",
      dG = "u234",
      dH = "2e6fdf69d4444916b4d8fad074bb2730",
      dI = "u235",
      dJ = "5b589a1121924bb8977c40c1ce35702e",
      dK = "u236",
      dL = "e79bb0f073a74f05bf68ccaeacb3f0d7",
      dM = "u237",
      dN = "201fb085a7834ae5bc02792d58719453",
      dO = "u238",
      dP = "12d97b01c67f4e97ba79c7a8f3691a19",
      dQ = "u239",
      dR = "2f93abfd602f4e199ef4271ce40617d2",
      dS = "u240";
    return _creator();
  })(),
);
