$axure.loadCurrentPage(
  (function () {
    var _ = function () {
      var r = {},
        a = arguments;
      for (var i = 0; i < a.length; i += 2) r[a[i]] = a[i + 1];
      return r;
    };
    var _creator = function () {
      return _(
        b,
        c,
        d,
        e,
        f,
        _(g, h, i, _(j, k, l, k)),
        m,
        [],
        n,
        _(h, o),
        p,
        [q],
        r,
        _(
          s,
          t,
          u,
          v,
          g,
          w,
          x,
          _(),
          y,
          [],
          z,
          _(
            A,
            B,
            C,
            D,
            E,
            _(F, G, H, I),
            J,
            null,
            K,
            L,
            L,
            M,
            N,
            O,
            null,
            P,
            Q,
            R,
            S,
            T,
            U,
            V,
            Q,
            W,
            X,
            _(F, G, H, Y),
            Z,
            Q,
            ba,
            bb,
            _(
              bc,
              bd,
              be,
              bf,
              bg,
              bf,
              bh,
              bf,
              bi,
              k,
              H,
              _(bj, bk, bl, bk, bm, bk, bn, bo),
            ),
            i,
            _(j, k, l, k),
          ),
          bp,
          _(),
          bq,
          _(),
          br,
          _(bs, [
            _(
              bt,
              bu,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                i,
                _(j, bC, l, bD),
                A,
                bE,
                X,
                _(F, G, H, bF),
                E,
                _(F, G, H, bG),
                Z,
                bH,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              bK,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bL,
                bM,
                bN,
                _(F, G, H, I, bO, bP),
                i,
                _(j, bQ, l, bR),
                A,
                bS,
                bT,
                _(bU, bV, bW, bX),
                bY,
                D,
                bZ,
                ca,
                cb,
                cc,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              cd,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bN,
                _(F, G, H, bG, bO, bP),
                i,
                _(j, ce, l, cf),
                A,
                cg,
                bT,
                _(bU, ch, bW, ci),
                bZ,
                cj,
                bY,
                D,
                cb,
                cc,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              ck,
              bv,
              h,
              bw,
              cl,
              u,
              cm,
              bz,
              cm,
              bA,
              bB,
              z,
              _(
                i,
                _(j, cn, l, co),
                cp,
                _(cq, _(A, cr), cs, _(A, ct)),
                A,
                cu,
                bT,
                _(bU, cv, bW, cw),
                Z,
                cx,
                bZ,
                cj,
              ),
              cy,
              bd,
              bp,
              _(),
              bI,
              _(),
              cz,
              cA,
            ),
            _(
              bt,
              cB,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bN,
                _(F, G, H, bG, bO, bP),
                i,
                _(j, ce, l, cf),
                A,
                cg,
                bT,
                _(bU, ch, bW, cC),
                bZ,
                cj,
                bY,
                D,
                cb,
                cc,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              cD,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                i,
                _(j, cE, l, co),
                A,
                cF,
                bT,
                _(bU, cG, bW, cH),
                bZ,
                cI,
                cp,
                _(cJ, _(E, _(F, G, H, cK))),
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              cL,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bN,
                _(F, G, H, bG, bO, bP),
                i,
                _(j, ce, l, cf),
                A,
                cg,
                bT,
                _(bU, ch, bW, cM),
                bZ,
                cj,
                bY,
                D,
                cb,
                cc,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              cN,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                i,
                _(j, cO, l, cE),
                A,
                cF,
                bT,
                _(bU, cP, bW, cQ),
                bZ,
                cR,
                cp,
                _(cJ, _(E, _(F, G, H, cK))),
              ),
              bp,
              _(),
              bI,
              _(),
              bq,
              _(
                cS,
                _(cT, cU, cV, cW, cX, [
                  _(cV, h, cY, h, cZ, bd, da, db, dc, [
                    _(
                      dd,
                      de,
                      cV,
                      df,
                      dg,
                      dh,
                      di,
                      _(dj, _(h, df)),
                      dk,
                      _(dl, r, b, dm, dn, bB),
                      dp,
                      dq,
                    ),
                  ]),
                ]),
              ),
              dr,
              bB,
              bJ,
              bd,
            ),
            _(
              bt,
              ds,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bN,
                _(F, G, H, bG, bO, bP),
                i,
                _(j, ce, l, cf),
                A,
                cg,
                bT,
                _(bU, ch, bW, dt),
                bZ,
                cj,
                bY,
                D,
                cb,
                cc,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              du,
              bv,
              h,
              bw,
              dv,
              u,
              dw,
              bz,
              dw,
              bA,
              bB,
              z,
              _(
                i,
                _(j, dx, l, co),
                A,
                dy,
                cp,
                _(cs, _(A, ct)),
                bT,
                _(bU, cv, bW, dz),
              ),
              cy,
              bd,
              bp,
              _(),
              bI,
              _(),
            ),
            _(
              bt,
              dA,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bN,
                _(F, G, H, bG, bO, bP),
                i,
                _(j, dB, l, co),
                A,
                cg,
                bT,
                _(bU, ci, bW, dC),
                bZ,
                cj,
                bY,
                D,
                cb,
                cc,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              dD,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bN,
                _(F, G, H, bG, bO, bP),
                i,
                _(j, dB, l, co),
                A,
                cg,
                bT,
                _(bU, dE, bW, dC),
                bZ,
                cj,
                bY,
                D,
                cb,
                cc,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              dF,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bN,
                _(F, G, H, bG, bO, bP),
                i,
                _(j, dB, l, co),
                A,
                cg,
                bT,
                _(bU, dG, bW, dC),
                bZ,
                cj,
                bY,
                D,
                cb,
                cc,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              dH,
              bv,
              h,
              bw,
              dv,
              u,
              dw,
              bz,
              dw,
              bA,
              bB,
              z,
              _(
                i,
                _(j, bD, l, co),
                A,
                dy,
                cp,
                _(cs, _(A, ct)),
                bT,
                _(bU, dI, bW, dC),
              ),
              cy,
              bd,
              bp,
              _(),
              bI,
              _(),
            ),
            _(
              bt,
              dJ,
              bv,
              h,
              bw,
              dv,
              u,
              dw,
              bz,
              dw,
              bA,
              bB,
              z,
              _(
                i,
                _(j, bD, l, co),
                A,
                dy,
                cp,
                _(cs, _(A, ct)),
                bT,
                _(bU, dK, bW, dC),
              ),
              cy,
              bd,
              bp,
              _(),
              bI,
              _(),
            ),
            _(
              bt,
              dL,
              bv,
              h,
              bw,
              dv,
              u,
              dw,
              bz,
              dw,
              bA,
              bB,
              z,
              _(
                i,
                _(j, bD, l, co),
                A,
                dy,
                cp,
                _(cs, _(A, ct)),
                bT,
                _(bU, dM, bW, dC),
              ),
              cy,
              bd,
              bp,
              _(),
              bI,
              _(),
            ),
            _(
              bt,
              dN,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bN,
                _(F, G, H, bG, bO, bP),
                i,
                _(j, dB, l, co),
                A,
                cg,
                bT,
                _(bU, dO, bW, dP),
                bZ,
                cj,
                bY,
                D,
                cb,
                cc,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              dQ,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bN,
                _(F, G, H, bG, bO, bP),
                i,
                _(j, dB, l, co),
                A,
                cg,
                bT,
                _(bU, dE, bW, dP),
                bZ,
                cj,
                bY,
                D,
                cb,
                cc,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              dR,
              bv,
              h,
              bw,
              dv,
              u,
              dw,
              bz,
              dw,
              bA,
              bB,
              z,
              _(
                i,
                _(j, bD, l, co),
                A,
                dy,
                cp,
                _(cs, _(A, ct)),
                bT,
                _(bU, dI, bW, dP),
              ),
              cy,
              bd,
              bp,
              _(),
              bI,
              _(),
            ),
            _(
              bt,
              dS,
              bv,
              h,
              bw,
              dv,
              u,
              dw,
              bz,
              dw,
              bA,
              bB,
              z,
              _(
                i,
                _(j, bD, l, co),
                A,
                dy,
                cp,
                _(cs, _(A, ct)),
                bT,
                _(bU, dM, bW, dP),
              ),
              cy,
              bd,
              bp,
              _(),
              bI,
              _(),
            ),
            _(
              bt,
              dT,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                i,
                _(j, cE, l, co),
                A,
                cF,
                bT,
                _(bU, cG, bW, dU),
                bZ,
                cI,
                bO,
                dV,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              dW,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bN,
                _(F, G, H, bG, bO, bP),
                i,
                _(j, ce, l, cf),
                A,
                cg,
                bT,
                _(bU, ch, bW, dX),
                bZ,
                cj,
                bY,
                D,
                cb,
                cc,
                bO,
                dV,
              ),
              bp,
              _(),
              bI,
              _(),
              bJ,
              bd,
            ),
            _(
              bt,
              dY,
              bv,
              h,
              bw,
              dv,
              u,
              dw,
              bz,
              dw,
              bA,
              bB,
              z,
              _(
                i,
                _(j, dx, l, co),
                A,
                dy,
                cp,
                _(cs, _(A, ct)),
                bT,
                _(bU, cv, bW, dZ),
                bO,
                dV,
              ),
              cy,
              bd,
              bp,
              _(),
              bI,
              _(),
            ),
            _(
              bt,
              ea,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                i,
                _(j, cO, l, cE),
                A,
                cF,
                bT,
                _(bU, eb, bW, cQ),
                bZ,
                cR,
                cp,
                _(cJ, _(E, _(F, G, H, cK))),
              ),
              bp,
              _(),
              bI,
              _(),
              bq,
              _(
                cS,
                _(cT, cU, cV, cW, cX, [
                  _(cV, h, cY, h, cZ, bd, da, db, dc, [
                    _(
                      dd,
                      de,
                      cV,
                      df,
                      dg,
                      dh,
                      di,
                      _(dj, _(h, df)),
                      dk,
                      _(dl, r, b, dm, dn, bB),
                      dp,
                      dq,
                    ),
                  ]),
                ]),
              ),
              dr,
              bB,
              bJ,
              bd,
            ),
          ]),
        ),
        ec,
        _(),
        ed,
        _(
          ee,
          _(ef, eg),
          eh,
          _(ef, ei),
          ej,
          _(ef, ek),
          el,
          _(ef, em),
          en,
          _(ef, eo),
          ep,
          _(ef, eq),
          er,
          _(ef, es),
          et,
          _(ef, eu),
          ev,
          _(ef, ew),
          ex,
          _(ef, ey),
          ez,
          _(ef, eA),
          eB,
          _(ef, eC),
          eD,
          _(ef, eE),
          eF,
          _(ef, eG),
          eH,
          _(ef, eI),
          eJ,
          _(ef, eK),
          eL,
          _(ef, eM),
          eN,
          _(ef, eO),
          eP,
          _(ef, eQ),
          eR,
          _(ef, eS),
          eT,
          _(ef, eU),
          eV,
          _(ef, eW),
          eX,
          _(ef, eY),
          eZ,
          _(ef, fa),
        ),
      );
    };
    var b = "url",
      c = "add_job.html",
      d = "generationDate",
      e = new Date(1721496785590.97),
      f = "defaultAdaptiveView",
      g = "name",
      h = "",
      i = "size",
      j = "width",
      k = 0,
      l = "height",
      m = "adaptiveViews",
      n = "sketchKeys",
      o = "s0",
      p = "variables",
      q = "OnLoadVariable",
      r = "page",
      s = "packageId",
      t = "b2d4096516bb4985a0fffa4f7f6f5bb1",
      u = "type",
      v = "Axure:Page",
      w = "Add Job",
      x = "notes",
      y = "annotations",
      z = "style",
      A = "baseStyle",
      B = "627587b6038d43cca051c114ac41ad32",
      C = "pageAlignment",
      D = "center",
      E = "fill",
      F = "fillType",
      G = "solid",
      H = "color",
      I = 0xffffffff,
      J = "image",
      K = "imageAlignment",
      L = "near",
      M = "imageRepeat",
      N = "auto",
      O = "favicon",
      P = "sketchFactor",
      Q = "0",
      R = "colorStyle",
      S = "appliedColor",
      T = "fontName",
      U = "Applied Font",
      V = "borderWidth",
      W = "borderVisibility",
      X = "borderFill",
      Y = 0xff797979,
      Z = "cornerRadius",
      ba = "cornerVisibility",
      bb = "outerShadow",
      bc = "on",
      bd = false,
      be = "offsetX",
      bf = 5,
      bg = "offsetY",
      bh = "blurRadius",
      bi = "spread",
      bj = "r",
      bk = 0,
      bl = "g",
      bm = "b",
      bn = "a",
      bo = 0.349019607843137,
      bp = "adaptiveStyles",
      bq = "interactionMap",
      br = "diagram",
      bs = "objects",
      bt = "id",
      bu = "ead641e326dd46c7a2578008d60e53eb",
      bv = "label",
      bw = "friendlyType",
      bx = "Rectangle",
      by = "vectorShape",
      bz = "styleType",
      bA = "visible",
      bB = true,
      bC = 999,
      bD = 80,
      bE = "4b7bfc596114427989e10bb0b557d0ce",
      bF = 0xff00000a,
      bG = 0xff039d12,
      bH = "10",
      bI = "imageOverrides",
      bJ = "generateCompound",
      bK = "160c639087474aafbfc4b70df29eafc8",
      bL = "fontWeight",
      bM = "700",
      bN = "foreGroundFill",
      bO = "opacity",
      bP = 1,
      bQ = 961,
      bR = 38,
      bS = "1111111151944dfba49f67fd55eb1f88",
      bT = "location",
      bU = "x",
      bV = 19,
      bW = "y",
      bX = 21,
      bY = "horizontalAlignment",
      bZ = "fontSize",
      ca = "36px",
      cb = "verticalAlignment",
      cc = "middle",
      cd = "f997d031f6144970b17ffb80a1da9546",
      ce = 195,
      cf = 30,
      cg = "2285372321d148ec80932747449c36c9",
      ch = 70,
      ci = 160,
      cj = "19px",
      ck = "68439480cf8645459f0921ddee57ee8f",
      cl = "Text Field",
      cm = "textBox",
      cn = 630,
      co = 35,
      cp = "stateStyles",
      cq = "hint",
      cr = "4889d666e8ad4c5e81e59863039a5cc0",
      cs = "disabled",
      ct = "9bd0236217a94d89b0314c8c7fc75f16",
      cu = "44157808f2934100b68f2394a66b2bba",
      cv = 300,
      cw = 158,
      cx = "4",
      cy = "HideHintOnFocused",
      cz = "placeholderText",
      cA = "Escriba el nombre de su trabajo",
      cB = "d00fdb92f59546b2863f69a0f6e0b5b2",
      cC = 220,
      cD = "b40aebdf78474886804a98e198f3250b",
      cE = 40,
      cF = "cd64754845384de3872fb4a066432c1f",
      cG = 890,
      cH = 260,
      cI = "23px",
      cJ = "mouseOver",
      cK = 0xff0000ff,
      cL = "8dc700d6b71d464f93a9014d4dbd83f7",
      cM = 370,
      cN = "c309d9808ca448a1a4cf7e64c59e4e6d",
      cO = 140,
      cP = 790,
      cQ = 548,
      cR = "17px",
      cS = "onClick",
      cT = "eventType",
      cU = "OnClick",
      cV = "description",
      cW = "Click or Tap",
      cX = "cases",
      cY = "conditionString",
      cZ = "isNewIfGroup",
      da = "caseColorHex",
      db = "AB68FF",
      dc = "actions",
      dd = "action",
      de = "linkWindow",
      df = "Open Jobs Lists in Current Window",
      dg = "displayName",
      dh = "Open Link",
      di = "actionInfoDescriptions",
      dj = "Jobs Lists",
      dk = "target",
      dl = "targetType",
      dm = "jobs_lists.html",
      dn = "includeVariables",
      dp = "linkType",
      dq = "current",
      dr = "tabbable",
      ds = "0d7842b10af846599f7019b5769bde5a",
      dt = 263,
      du = "2ac1e7d5272d4e739cb5bda6a473794d",
      dv = "Droplist",
      dw = "comboBox",
      dx = 580,
      dy = "85f724022aae41c594175ddac9c289eb",
      dz = 261,
      dA = "75edcc7fde2e4ccd909c055f7cb4e8f7",
      dB = 90,
      dC = 406,
      dD = "00d0226f62454b629908760aca5d90cd",
      dE = 390,
      dF = "d0660558fb884bc3902c17a6c529a893",
      dG = 620,
      dH = "454d37a9d5b746d1951c85a7f0c260fc",
      dI = 280,
      dJ = "d6f9942dc67e43058c79af242de1239b",
      dK = 740,
      dL = "51a2dcbbc6c14a90ab839082a6096650",
      dM = 510,
      dN = "2fcc57676d984c8baee6f78972f98d16",
      dO = 168,
      dP = 483,
      dQ = "bfd3019b76b14b6d9c50a6dac5a543f9",
      dR = "24aa306f936140048b52d4f8acf8dff4",
      dS = "bb29aaa99f634222bb58b67f83316003",
      dT = "fa612b4830da4ad9a201fe9b8fffa9c5",
      dU = 310,
      dV = "0.28",
      dW = "e12148b3b18e44769db0e91e2df3802e",
      dX = 313,
      dY = "efa91471775342ea823d8d8144be29f7",
      dZ = 311,
      ea = "f0a158469a2f4917849bf85fba436129",
      eb = 98,
      ec = "masters",
      ed = "objectPaths",
      ee = "ead641e326dd46c7a2578008d60e53eb",
      ef = "scriptId",
      eg = "u124",
      eh = "160c639087474aafbfc4b70df29eafc8",
      ei = "u125",
      ej = "f997d031f6144970b17ffb80a1da9546",
      ek = "u126",
      el = "68439480cf8645459f0921ddee57ee8f",
      em = "u127",
      en = "d00fdb92f59546b2863f69a0f6e0b5b2",
      eo = "u128",
      ep = "b40aebdf78474886804a98e198f3250b",
      eq = "u129",
      er = "8dc700d6b71d464f93a9014d4dbd83f7",
      es = "u130",
      et = "c309d9808ca448a1a4cf7e64c59e4e6d",
      eu = "u131",
      ev = "0d7842b10af846599f7019b5769bde5a",
      ew = "u132",
      ex = "2ac1e7d5272d4e739cb5bda6a473794d",
      ey = "u133",
      ez = "75edcc7fde2e4ccd909c055f7cb4e8f7",
      eA = "u134",
      eB = "00d0226f62454b629908760aca5d90cd",
      eC = "u135",
      eD = "d0660558fb884bc3902c17a6c529a893",
      eE = "u136",
      eF = "454d37a9d5b746d1951c85a7f0c260fc",
      eG = "u137",
      eH = "d6f9942dc67e43058c79af242de1239b",
      eI = "u138",
      eJ = "51a2dcbbc6c14a90ab839082a6096650",
      eK = "u139",
      eL = "2fcc57676d984c8baee6f78972f98d16",
      eM = "u140",
      eN = "bfd3019b76b14b6d9c50a6dac5a543f9",
      eO = "u141",
      eP = "24aa306f936140048b52d4f8acf8dff4",
      eQ = "u142",
      eR = "bb29aaa99f634222bb58b67f83316003",
      eS = "u143",
      eT = "fa612b4830da4ad9a201fe9b8fffa9c5",
      eU = "u144",
      eV = "e12148b3b18e44769db0e91e2df3802e",
      eW = "u145",
      eX = "efa91471775342ea823d8d8144be29f7",
      eY = "u146",
      eZ = "f0a158469a2f4917849bf85fba436129",
      fa = "u147";
    return _creator();
  })(),
);
