$axure.loadCurrentPage(
  (function () {
    var _ = function () {
      var r = {},
        a = arguments;
      for (var i = 0; i < a.length; i += 2) r[a[i]] = a[i + 1];
      return r;
    };
    var _creator = function () {
      return _(
        b,
        c,
        d,
        e,
        f,
        _(g, h, i, _(j, k, l, k)),
        m,
        [],
        n,
        _(h, o),
        p,
        [q],
        r,
        _(
          s,
          t,
          u,
          v,
          g,
          w,
          x,
          _(),
          y,
          [],
          z,
          _(
            A,
            B,
            C,
            D,
            E,
            _(F, G, H, I),
            J,
            null,
            K,
            L,
            L,
            M,
            N,
            O,
            null,
            P,
            Q,
            R,
            S,
            T,
            U,
            V,
            Q,
            W,
            X,
            _(F, G, H, Y),
            Z,
            Q,
            ba,
            bb,
            _(
              bc,
              bd,
              be,
              bf,
              bg,
              bf,
              bh,
              bf,
              bi,
              k,
              H,
              _(bj, bk, bl, bk, bm, bk, bn, bo),
            ),
            i,
            _(j, k, l, k),
          ),
          bp,
          _(),
          bq,
          _(),
          br,
          _(bs, [
            _(
              bt,
              bu,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bC,
                bD,
                bE,
                _(F, G, H, I, bF, bG),
                i,
                _(j, bH, l, bI),
                A,
                bJ,
                X,
                _(F, G, H, bK),
                E,
                _(F, G, H, bL),
                Z,
                bM,
                bN,
                bO,
              ),
              bp,
              _(),
              bP,
              _(),
              bQ,
              bd,
            ),
            _(
              bt,
              bR,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bE,
                _(F, G, H, bL, bF, bG),
                i,
                _(j, bS, l, bT),
                A,
                bU,
                bV,
                _(bW, bX, bY, bZ),
                bN,
                ca,
                cb,
                D,
                cc,
                cd,
              ),
              bp,
              _(),
              bP,
              _(),
              bQ,
              bd,
            ),
            _(
              bt,
              ce,
              bv,
              h,
              bw,
              cf,
              u,
              cg,
              bz,
              cg,
              bA,
              bB,
              z,
              _(
                i,
                _(j, ch, l, ci),
                cj,
                _(ck, _(A, cl), cm, _(A, cn)),
                A,
                co,
                bV,
                _(bW, cp, bY, cq),
                Z,
                cr,
                bN,
                ca,
              ),
              cs,
              bd,
              bp,
              _(),
              bP,
              _(),
              ct,
              cu,
            ),
            _(
              bt,
              cv,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                i,
                _(j, cw, l, cx),
                A,
                cy,
                bV,
                _(bW, cz, bY, cA),
                bN,
                cB,
                cj,
                _(cC, _(E, _(F, G, H, cD))),
              ),
              bp,
              _(),
              bP,
              _(),
              bq,
              _(
                cE,
                _(cF, cG, cH, cI, cJ, [
                  _(cH, h, cK, h, cL, bd, cM, cN, cO, [
                    _(
                      cP,
                      cQ,
                      cH,
                      cR,
                      cS,
                      cT,
                      cU,
                      _(cV, _(h, cR)),
                      cW,
                      _(cX, r, b, cY, cZ, bB),
                      da,
                      db,
                    ),
                  ]),
                ]),
              ),
              dc,
              bB,
              bQ,
              bd,
            ),
            _(
              bt,
              dd,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                i,
                _(j, cw, l, cx),
                A,
                cy,
                bV,
                _(bW, de, bY, cA),
                bN,
                cB,
                cj,
                _(cC, _(E, _(F, G, H, cD))),
              ),
              bp,
              _(),
              bP,
              _(),
              bq,
              _(
                cE,
                _(cF, cG, cH, cI, cJ, [
                  _(cH, h, cK, h, cL, bd, cM, cN, cO, [
                    _(
                      cP,
                      cQ,
                      cH,
                      cR,
                      cS,
                      cT,
                      cU,
                      _(cV, _(h, cR)),
                      cW,
                      _(cX, r, b, cY, cZ, bB),
                      da,
                      db,
                    ),
                  ]),
                ]),
              ),
              dc,
              bB,
              bQ,
              bd,
            ),
            _(
              bt,
              df,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bE,
                _(F, G, H, bL, bF, bG),
                i,
                _(j, bS, l, bT),
                A,
                bU,
                bV,
                _(bW, bX, bY, dg),
                bN,
                ca,
                cb,
                D,
                cc,
                cd,
              ),
              bp,
              _(),
              bP,
              _(),
              bQ,
              bd,
            ),
            _(
              bt,
              dh,
              bv,
              h,
              bw,
              cf,
              u,
              cg,
              bz,
              cg,
              bA,
              bB,
              z,
              _(
                i,
                _(j, ch, l, ci),
                cj,
                _(ck, _(A, cl), cm, _(A, cn)),
                A,
                co,
                bV,
                _(bW, cp, bY, di),
                Z,
                cr,
                bN,
                ca,
              ),
              cs,
              bd,
              bp,
              _(),
              bP,
              _(),
              ct,
              dj,
            ),
            _(
              bt,
              dk,
              bv,
              h,
              bw,
              bx,
              u,
              by,
              bz,
              by,
              bA,
              bB,
              z,
              _(
                bE,
                _(F, G, H, bL, bF, bG),
                i,
                _(j, bS, l, bT),
                A,
                bU,
                bV,
                _(bW, bX, bY, dl),
                bN,
                ca,
                cb,
                D,
                cc,
                cd,
              ),
              bp,
              _(),
              bP,
              _(),
              bQ,
              bd,
            ),
            _(
              bt,
              dm,
              bv,
              h,
              bw,
              cf,
              u,
              cg,
              bz,
              cg,
              bA,
              bB,
              z,
              _(
                i,
                _(j, ch, l, ci),
                cj,
                _(ck, _(A, cl), cm, _(A, cn)),
                A,
                co,
                bV,
                _(bW, cp, bY, dn),
                Z,
                cr,
                bN,
                ca,
              ),
              cs,
              bd,
              bp,
              _(),
              bP,
              _(),
              ct,
              dp,
            ),
          ]),
        ),
        dq,
        _(),
        dr,
        _(
          ds,
          _(dt, du),
          dv,
          _(dt, dw),
          dx,
          _(dt, dy),
          dz,
          _(dt, dA),
          dB,
          _(dt, dC),
          dD,
          _(dt, dE),
          dF,
          _(dt, dG),
          dH,
          _(dt, dI),
          dJ,
          _(dt, dK),
        ),
      );
    };
    var b = "url",
      c = "update_llm.html",
      d = "generationDate",
      e = new Date(1721496785718.48),
      f = "defaultAdaptiveView",
      g = "name",
      h = "",
      i = "size",
      j = "width",
      k = 0,
      l = "height",
      m = "adaptiveViews",
      n = "sketchKeys",
      o = "s0",
      p = "variables",
      q = "OnLoadVariable",
      r = "page",
      s = "packageId",
      t = "da5ec07962554ee28c0519379a37fe48",
      u = "type",
      v = "Axure:Page",
      w = "Update LLM",
      x = "notes",
      y = "annotations",
      z = "style",
      A = "baseStyle",
      B = "627587b6038d43cca051c114ac41ad32",
      C = "pageAlignment",
      D = "center",
      E = "fill",
      F = "fillType",
      G = "solid",
      H = "color",
      I = 0xffffffff,
      J = "image",
      K = "imageAlignment",
      L = "near",
      M = "imageRepeat",
      N = "auto",
      O = "favicon",
      P = "sketchFactor",
      Q = "0",
      R = "colorStyle",
      S = "appliedColor",
      T = "fontName",
      U = "Applied Font",
      V = "borderWidth",
      W = "borderVisibility",
      X = "borderFill",
      Y = 0xff797979,
      Z = "cornerRadius",
      ba = "cornerVisibility",
      bb = "outerShadow",
      bc = "on",
      bd = false,
      be = "offsetX",
      bf = 5,
      bg = "offsetY",
      bh = "blurRadius",
      bi = "spread",
      bj = "r",
      bk = 0,
      bl = "g",
      bm = "b",
      bn = "a",
      bo = 0.349019607843137,
      bp = "adaptiveStyles",
      bq = "interactionMap",
      br = "diagram",
      bs = "objects",
      bt = "id",
      bu = "db41e60026ba41e19e25a302e40c853b",
      bv = "label",
      bw = "friendlyType",
      bx = "Rectangle",
      by = "vectorShape",
      bz = "styleType",
      bA = "visible",
      bB = true,
      bC = "fontWeight",
      bD = "700",
      bE = "foreGroundFill",
      bF = "opacity",
      bG = 1,
      bH = 999,
      bI = 80,
      bJ = "4b7bfc596114427989e10bb0b557d0ce",
      bK = 0xff00000a,
      bL = 0xff039d12,
      bM = "10",
      bN = "fontSize",
      bO = "36px",
      bP = "imageOverrides",
      bQ = "generateCompound",
      bR = "3d1d34f783f0443298dd87225851e91d",
      bS = 195,
      bT = 30,
      bU = "2285372321d148ec80932747449c36c9",
      bV = "location",
      bW = "x",
      bX = 70,
      bY = "y",
      bZ = 160,
      ca = "19px",
      cb = "horizontalAlignment",
      cc = "verticalAlignment",
      cd = "middle",
      ce = "557eca5a068b44f38530d5454d7d7052",
      cf = "Text Field",
      cg = "textBox",
      ch = 630,
      ci = 35,
      cj = "stateStyles",
      ck = "hint",
      cl = "4889d666e8ad4c5e81e59863039a5cc0",
      cm = "disabled",
      cn = "9bd0236217a94d89b0314c8c7fc75f16",
      co = "44157808f2934100b68f2394a66b2bba",
      cp = 300,
      cq = 158,
      cr = "4",
      cs = "HideHintOnFocused",
      ct = "placeholderText",
      cu = "Escriba el nombre de su LLM",
      cv = "74657a4da9ba43d9b582845868a254ca",
      cw = 140,
      cx = 40,
      cy = "cd64754845384de3872fb4a066432c1f",
      cz = 790,
      cA = 410,
      cB = "17px",
      cC = "mouseOver",
      cD = 0xff0000ff,
      cE = "onClick",
      cF = "eventType",
      cG = "OnClick",
      cH = "description",
      cI = "Click or Tap",
      cJ = "cases",
      cK = "conditionString",
      cL = "isNewIfGroup",
      cM = "caseColorHex",
      cN = "AB68FF",
      cO = "actions",
      cP = "action",
      cQ = "linkWindow",
      cR = "Open LLMs List in Current Window",
      cS = "displayName",
      cT = "Open Link",
      cU = "actionInfoDescriptions",
      cV = "LLMs List",
      cW = "target",
      cX = "targetType",
      cY = "llms_list.html",
      cZ = "includeVariables",
      da = "linkType",
      db = "current",
      dc = "tabbable",
      dd = "5ccf4119d5b44043be6926bb1ac0a6de",
      de = 98,
      df = "0d0d8af6aa494a678b0de8e2c58c85cd",
      dg = 217,
      dh = "75b66a2ffea44d6f86f5a7f2661329ba",
      di = 215,
      dj = "Escriba el URL de la API de su LLM",
      dk = "e030d74885f44275913afa72ccf30e9a",
      dl = 277,
      dm = "b2ae2c1c06ef465abad51f3a1c33493b",
      dn = 275,
      dp = "Escriba la API KEY de ser necesaria",
      dq = "masters",
      dr = "objectPaths",
      ds = "db41e60026ba41e19e25a302e40c853b",
      dt = "scriptId",
      du = "u241",
      dv = "3d1d34f783f0443298dd87225851e91d",
      dw = "u242",
      dx = "557eca5a068b44f38530d5454d7d7052",
      dy = "u243",
      dz = "74657a4da9ba43d9b582845868a254ca",
      dA = "u244",
      dB = "5ccf4119d5b44043be6926bb1ac0a6de",
      dC = "u245",
      dD = "0d0d8af6aa494a678b0de8e2c58c85cd",
      dE = "u246",
      dF = "75b66a2ffea44d6f86f5a7f2661329ba",
      dG = "u247",
      dH = "e030d74885f44275913afa72ccf30e9a",
      dI = "u248",
      dJ = "b2ae2c1c06ef465abad51f3a1c33493b",
      dK = "u249";
    return _creator();
  })(),
);
